### ISSUE TITLE
docker_registry_image : Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by dlaburthe** [kreuzwerker/terraform-provider-docker#192]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

Terraform v0.15.3
kreuzwerker/docker v2.11.0

### Affected Resource(s)

* `docker_registry_image`

### Terraform Configuration Files

```hcl
resource "docker_registry_image" "images" {
  for_each = fileset("${path.cwd}/../../docker_files/", "*.dockerfile")

  name          = "${aws_ecr_repository.repo.repository_url}:${basename(trimsuffix(each.key, ".dockerfile"))}"
  keep_remotely = true

  build {
    context    = "${trimsuffix(path.cwd, "/terraform/main")}/docker_files/"
    dockerfile = each.key
  }
}
```

### Debug Output

https://gist.github.com/dlaburthe/ba6b1e2e114ab96914a378045e14f2ea

### Expected Behaviour

The images should have been built and deployed to the ECR registry.

### Actual Behaviour

```
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ docker_registry_image.images["image.dockerfile"] to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/kreuzwerker/docker" produced an invalid new value
│ for .build[0].context: was
│ cty.StringVal("/opt/atlassian/pipelines/agent/build/docker_files/:e749c755d7c464779e052dea6d4526f0d8dfb7ba4e33d72794cf8b508f795047"),
│ but now
│ cty.StringVal("/opt/atlassian/pipelines/agent/build/docker_files/:ed66c6f3c8418a58bebf7ea7b560efebeac47857afa3780b485d9bfbf228a136").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```

### Steps to Reproduce

1. `terraform plan -out planfile`
2. `terraform apply planfile`

### Important Factoids

The execution process takes place in a bitbucket pipeline via two separate steps.
```
pipelines:
  custom:
    1.PLAN_APPLY:
      - step:
          name: Terraform plan
          artifacts:
            - terraform/main/.out/*.plan
          script:
            - ./scripts/deploy_terraform.sh plan
          services:
            - docker
      - step:
          name: Terraform apply
          trigger: manual
          script:
            - ./scripts/deploy_terraform.sh apply
          services:
            - docker
```
